### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by IzzySoft** [roozbehzarei/filester#50]
Our scanners reported the [Aptabase](https://github.com/aptabase/aptabase) library in your app, which is for mobile analytics. As I could not find any hint in your Readme: is the collection opt-in, or is it enabled by default? Are users informed what data is being collected? Is the Aptabase server self-hosted? Thanks in advance for clarification!

**Comment by licaon-kter** [comment]
Added AFs for F-Droid https://gitlab.com/fdroid/fdroiddata/-/commit/123e7e9fb1a5086c04c14e913d6908377a4e62f2

**Comment by IzzySoft** [comment]
At IzzyOnDroid, AFs have been updated now too, effective with the next sync around 7 pm UTC. We (F-Droid and IzzyOnDroid) will of course "clear up" should the situation change – e.g. Aptabase becoming strictly opt-in.

```yaml
AntiFeatures:
  NonFreeNet:
    en-US: The app connects to Github.
    de: Die App baut Verbindungen zu Github auf.
  TetheredNet:
    en-US: The app depends on transfer.sh and uses Aptabase.
    de: Die App hängt ist auf transfer.sh angewiesen und verwendet Aptabase.
  Tracking:
    en-US: The app uses Aptabase analytics, which cannot be disabled.
    de: Die App verwendet Analytics von Aptabase, die nicht deaktiviert werden können.
```
